### ISSUE TITLE
Add support for no compression

### ISSUE THREAD

**Issue by darrylmasson** [AxFoundation/redax#3]
It could be useful somehow.

**Comment by jorana** [comment]
Perhaps we could also then add a switch between LZ4/blosc depending on the expected datarate. For BG it should be low. For calibration it should be high. Could of course go in the config too.

**Comment by darrylmasson** [comment]
You might not know ahead of time what rate you're going to have in a given run, and if you get it wrong then redax dies.

In the current deployment we could switch back to blosc, the only way we hit the 2G limit per subchunk is if things go _catastrophically_ wrong. Even under the heaviest load, with the typical configuration each subchunk would total 50 MB.

**Comment by jorana** [comment]
but you know for a BG run we never going to hit this. It's only very heavy calibration runs where you are going to have the possibility to run into this issue.

**Comment by darrylmasson** [comment]
The "typical" config uses 24 processing threads/host. The highest rates we've tested were 250 MB/s/host, which is 10 MB/s/thread. Unless the chunks last for minutes, and several PMTs flash, and we get a bunch of muons at the same time, there's no way we'll get even anywhere near 1 GB/subchunk.
