### ISSUE TITLE
#43 makes strange format

### ISSUE THREAD

**Issue by jorana** [AxFoundation/redax#48]
@darrylmasson , @petergaemers , this does not seem like the intend outcome of #43 
![afbeelding](https://user-images.githubusercontent.com/22295914/115950044-2d4fe000-a4d9-11eb-96bc-d082a1d6933f.png)

Also the other documents have not been updated.

**Comment by darrylmasson** [comment]
This was the intended outcome, the problem was that I didn't update the configs (or the rundocs, mea culpa)
