### ISSUE TITLE
Don't allow logs to re-use the same print statement

### ISSUE THREAD

**Issue by jorana** [AxFoundation/redax#52]
All print statements should be (relatively) unique, if we spend 10 minutes looking which if statement we are at we have not set up our logging correctly

**Comment by darrylmasson** [comment]
Alternately, we add the line number to the log output, and all ambiguity vanishes.

**Comment by jorana** [comment]
I like this idea

**Comment by darrylmasson** [comment]
Closed via https://github.com/XENONnT/daqnt/pull/53
