### ISSUE TITLE
Compilation issue/question

### ISSUE THREAD

**Issue by AlexElykov** [AxFoundation/redax#62]
https://github.com/AxFoundation/redax/blob/0cdcf6a683aaf5a4aedd4ec7d55d31136a3cdccd/StraxFormatter.cc#L319-L325

@darrylmasson Are you sure this code here actually works with latest lz4?
 
Just tried to compile redax from scratch today, and was getting an
`error: braces around scalar initializer for type ‘unsigned int’ };` error, until I've changed the format to the exact one from frameCompress.c in lz4 examples. 

Never really looked into the straxformatting/compression part much before, so not really sure how these options should be actually implemented.

**Comment by darrylmasson** [comment]
Have you read the block comment 30 lines below this?

**Comment by AlexElykov** [comment]
Lol, ok I did now.

**Comment by darrylmasson** [comment]
As I think about it, either the comment should move or the declaration of this object should move. There's no reason for it to be `static const`
